// the real alerts object for tesing
export const alerts = [
  {
    id: '1',
    description:
      'Filesystem on /dev/vdc2 at 192.168.1.6:9100 has only 0.00% available space left.',
    documentationUrl: '',
    summary: 'Filesystem has less than 3% space left.',
    startsAt: '2021-01-18T16:43:35.358Z',
    endsAt: '2021-01-21T09:32:35.358Z',
    labels: {
      alertname: 'NodeFilesystemAlmostOutOfSpace',
      container: 'node-exporter',
      device: '/dev/vdc2',
      endpoint: 'metrics',
      fstype: 'ext4',
      instance: '192.168.1.6:9100',
      job: 'node-exporter',
      mountpoint: '/mnt/testpart2',
      namespace: 'metalk8s-monitoring',
      pod: 'prometheus-operator-prometheus-node-exporter-m9qcj',
      prometheus: 'metalk8s-monitoring/prometheus-operator-prometheus',
      service: 'prometheus-operator-prometheus-node-exporter',
      severity: 'critical',
    },
    severity: 'critical',
    originalAlert: {},
  },
  {
    id: '2',
    description:
      'Filesystem on /dev/vdc2 at 192.168.1.6:9100 has only 0.00% available space left.',
    documentationUrl: '',
    summary: 'Filesystem has less than 5% space left.',
    endsAt: '2021-01-21T09:32:35.358Z',
    startsAt: '2021-01-18T16:43:35.358Z',
    labels: {
      alertname: 'NodeFilesystemAlmostOutOfSpace',
      container: 'node-exporter',
      device: '/dev/vdc2',
      endpoint: 'metrics',
      fstype: 'ext4',
      instance: '192.168.1.6:9100',
      job: 'node-exporter',
      mountpoint: '/mnt/testpart2',
      namespace: 'metalk8s-monitoring',
      pod: 'prometheus-operator-prometheus-node-exporter-m9qcj',
      prometheus: 'metalk8s-monitoring/prometheus-operator-prometheus',
      service: 'prometheus-operator-prometheus-node-exporter',
      severity: 'warning',
    },
    severity: 'warning',
    originalAlert: {},
  },
  {
    id: '3',
    description:
      'Filesystem on /dev/vdc1 at 192.168.1.6:9100 has only 3.28% available space left.',
    documentationUrl: '',
    summary: 'Filesystem has less than 5% space left.',
    endsAt: '2021-01-21T09:32:35.358Z',
    startsAt: '2021-01-18T16:43:35.358Z',
    labels: {
      alertname: 'NodeFilesystemAlmostOutOfSpace',
      container: 'node-exporter',
      device: '/dev/vdc1',
      endpoint: 'metrics',
      fstype: 'xfs',
      instance: '192.168.1.6:9100',
      job: 'node-exporter',
      mountpoint: '/mnt/testpart1',
      namespace: 'metalk8s-monitoring',
      pod: 'prometheus-operator-prometheus-node-exporter-m9qcj',
      prometheus: 'metalk8s-monitoring/prometheus-operator-prometheus',
      service: 'prometheus-operator-prometheus-node-exporter',
      severity: 'warning',
    },
    severity: 'warning',
    originalAlert: {},
  },
];
