#!/bin/bash

set -e
set -u
set -o pipefail

cat << EOF
NAME=${NAME}
VERSION=${VERSION}
SHORT_VERSION=${SHORT_VERSION}
GIT=${GIT}
DEVELOPMENT_RELEASE=${DEVELOPMENT_RELEASE}
BUILD_TIMESTAMP=${BUILD_TIMESTAMP}
BUILD_HOST=${BUILD_HOST}
EOF
