version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@scality/core-ui"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
