default_language_version:
  python: python3.6

repos:
  - repo: https://github.com/psf/black
    # NOTE: Newer version does no longer support python3.6
    rev: 22.8.0
    hooks:
      - id: black
        name: Formatting Python
      - id: black
        # We want this hook to be part of "pylint" so that if we run
        # `pre-commit run pylint` we include this hook
        alias: pylint
        name: Checking Python formatting
        args:
          - --check
          - --diff

  - repo: https://github.com/pycqa/pylint
    rev: v2.9.5
    hooks:
      - id: pylint
        name: Lint Python (non-salt)
        # Linting for non-salt files (buildchain and python not executed
        # by salt directly)
        additional_dependencies:
          - 'pyenchant~=3.2'
          - 'doit~=0.32.0'
          - 'docker~=4.1.0'
          - 'PyYAML~=5.3.1'
          - 'pytest~=5.4'
          - 'Click~=8.0'
          - 'treelib~=1.6'
        files: >
          (?x)^(
              buildchain/dodo\.py|
              buildchain/buildchain/.*\.py|
              packages/debian/common/download_packages\.py|
              salt/metalk8s/volumes/files/sparse_volume_cleanup\.py|
              tools/lib-alert-tree/.*\.py
          )$
      - id: pylint
        name: Lint Salt
        # Linting for salt files only in directory "salt/_<module>/<module_name>.py"
        files: salt/_.*/.*\.py
        additional_dependencies: ['saltpylint==2020.9.28', 'six==1.15.0']
        args:
          - --rcfile=salt/.pylintrc
      - id: pylint
        name: Lint Salt Formulas tests
        files: salt/tests/unit/formulas/.*\.py
        additional_dependencies:
          - 'pyenchant~=3.2'
          - 'salt==3002.9'
          - pytest
          - Jinja2

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        # We want this hook to be part of "pylint" so that if we run
        # `pre-commit run pylint` we include this hook
        alias: pylint
        name: Python typing (buildchain)
        additional_dependencies:
          - 'types-PyYAML~=5.4'
        # Only check typing for typed files
        files: >
          (?x)^(
              buildchain/dodo.py|
              buildchain/buildchain/.*|
              packages/debian/common/download_packages.py
          )$
        args:
          - --strict
      - id: mypy
        # We want this hook to be part of "pylint" so that if we run
        # `pre-commit run pylint` we include this hook
        alias: pylint
        name: Python typing (formulas rendering tests)
        files: ^(salt/tests/unit/formulas/.*\.py)$
        args: [--strict]
        additional_dependencies:
          - 'pyenchant~=3.2'
          - 'types-PyYAML~=5.4'
          - 'types-Jinja2~=2.11'
          - pytest

  - repo: https://github.com/warpnet/salt-lint
    rev: v0.6.1
    hooks:
      - id: salt-lint

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.1
    hooks:
      - id: yamllint
        files: >
          (?x)^(
              salt/metalk8s/defaults.yaml|
              salt/tests/unit/formulas/.*\.yaml
          )$
