- hosts: localhost
  gather_facts: False
  any_errors_fatal: True
  roles:
    - role: preflight_checks
  tags:
    - preflight-checks

- hosts: k8s-cluster:etcd
  gather_facts: False
  tasks:
    - ping:

- hosts: k8s-cluster:etcd
  roles:
    - role: check_os

- hosts: k8s-cluster
  roles:
    - role: prepare_os

- hosts: kube-node
  tags:
    - lvm-storage
  roles:
    - role: setup_lvm

- hosts: k8s-cluster
  gather_facts: False
  tags:
    - kubespray
  roles:
    - role: kubespray/roles/kubespray-defaults/
    - role: kubespray_var_patcher

- import_playbook: 'kubespray/cluster.yml'
  tags: kubespray

- hosts: kube-node
  tags:
    - lvm-storage
    - kube-pv
  roles:
    - role: kube_lvm_storage

- hosts: kube-master
  gather_facts: False
  roles:
    - role: kube_nginx_ingress
      tags: ['ingress']
    - role: etcd_prometheus_exporter_cert
      tags: ['kube-prometheus']
    - role: kube_prometheus
      tags: ['kube-prometheus']
    - role: kube_heapster
      tags: ['heapster']
    - role: kube_elasticsearch
      tags: ['elasticsearch']
    - role: kube_metrics_server
      tags: ['metrics-server']

- hosts: k8s-cluster
  gather_facts: False
  tags: ['kubespray']
  roles:
    - role: info_displayer
      vars:
        add_info:
        - master_dashboard_url: >-
            {{ hostvars[groups['kube-master']|first].external_apiserver_endpoint
            }}/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy
          kube_login: 'kube'
          kube_password: '{{ kube_api_pwd }}'
