--- a/Dockerfile
+++ b/Dockerfile
@@ -15,6 +15,7 @@
 COPY cmd/main.go cmd/main.go
 COPY api/ api/
 COPY internal/ internal/
+COPY salt/ salt/
 
 # Build
 # the GOARCH has not a default value to allow the binary be built according to the host where the command
@@ -31,3 +32,40 @@
 USER 65532:65532
 
 ENTRYPOINT ["/manager"]
+
+# Timestamp of the build, formatted as RFC3339
+ARG BUILD_DATE
+# Git revision o the tree at build time
+ARG VCS_REF
+# Version of the image
+ARG VERSION
+# Version of the project, e.g. `git describe --always --long --dirty --broken`
+ARG METALK8S_VERSION
+
+# These contain BUILD_DATE so should come 'late' for layer caching
+LABEL maintainer="squad-metalk8s@scality.com" \
+      # http://label-schema.org/rc1/
+      org.label-schema.build-date="$BUILD_DATE" \
+      org.label-schema.name="storage-operator" \
+      org.label-schema.description="Kubernetes Operator for managing PersistentVolumes in MetalK8s" \
+      org.label-schema.url="https://github.com/scality/metalk8s/" \
+      org.label-schema.vcs-url="https://github.com/scality/metalk8s.git" \
+      org.label-schema.vcs-ref="$VCS_REF" \
+      org.label-schema.vendor="Scality" \
+      org.label-schema.version="$VERSION" \
+      org.label-schema.schema-version="1.0" \
+      # https://github.com/opencontainers/image-spec/blob/master/annotations.md
+      org.opencontainers.image.created="$BUILD_DATE" \
+      org.opencontainers.image.authors="squad-metalk8s@scality.com" \
+      org.opencontainers.image.url="https://github.com/scality/metalk8s/" \
+      org.opencontainers.image.source="https://github.com/scality/metalk8s.git" \
+      org.opencontainers.image.version="$VERSION" \
+      org.opencontainers.image.revision="$VCS_REF" \
+      org.opencontainers.image.vendor="Scality" \
+      org.opencontainers.image.title="storage-operator" \
+      org.opencontainers.image.description="Kubernetes Operator for managing PersistentVolumes in MetalK8s" \
+      # https://docs.openshift.org/latest/creating_images/metadata.html
+      io.openshift.tags="metalk8s,storage,operator" \
+      io.k8s.description="Kubernetes Operator for managing PersistentVolumes in MetalK8s" \
+      # Various
+      com.scality.metalk8s.version="$METALK8S_VERSION"
