import argparse
from typing import Any, Iterable, List, Union


class SaltCommandMixin(object):
    def __init__(self, args: argparse.Namespace) -> None: ...

    def run_salt_minion(self, cmd: Union[str, Iterable[str]]) -> str: ...

    def get_from_pillar(self, pillar_key: str) -> Any: ...

    def get_grain(self, grain_name: str, local: bool=False) -> Any: ...

    def run_salt_master(self, cmd: Union[str, Iterable[str]]) -> str: ...

    def build_cmd(self, executable: str, cmd: Union[str, Iterable[str]]) \
        -> List[str]: ...

    @property
    def saltenv(self) -> str: ...

    @staticmethod
    def get_salt_master_container() -> str: ...

    def check_on_bootstrap(self) -> None: ...
