resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: registry.metalk8s.lan/metalk8s-MK8S_VERSION_STUB/nginx-operator
  newTag: v4.11.3
