- name: 'create addons dir if needed'
  file:
    dest: '{{ nginx_ingress_addons_dir }}'
    state: directory

- name: 'template nginx monitoring manifests'
  template:
    src: '{{ item }}.j2'
    dest: '{{ nginx_ingress_addons_dir }}/{{ item }}'
  register: nginx_ingress_manifests
  with_items:
    - nginx_ingress_servicemonitor.yaml

- name: 'Nginx ingress monitoring: apply manifests'
  kube:
    kubectl: '{{ bin_dir }}/kubectl'
    filename: '{{ item.dest }}'
    namespace: '{{ kube_prometheus_namespace }}'
    state: 'latest'
  loop_control:
    label: '{{ item.dest }}'
  with_items: '{{ nginx_ingress_manifests.results|default([]) }}'
  run_once: True
