include:
  - metalk8s.kubernetes.gateway-api-crds.deployed
  - metalk8s.kubernetes.cni.cilium-crds.deployed
  - metalk8s.kubernetes.cni.cilium.deployed
  - metalk8s.kubernetes.cni.cilium-configuration.deployed
  - metalk8s.kubernetes.coredns.deployed
  - metalk8s.kubernetes.admin.deployed
  - metalk8s.repo.deployed
  - metalk8s.salt.master.deployed
  - metalk8s.backup.deployed
  - metalk8s.addons.metalk8s-operator.deployed
