#!/usr/bin/env python3
"""Print the kube-apiserver feature gates that break an upgrade.

The output is meant to replace the feature gate constants of
`salt/_runners/metalk8s_checks.py`, see BUMPING.md-->kubernetes.

A gate breaks the upgrade if kube-apiserver accepted it in the version we
upgrade from but refuses it in the version we upgrade to, because the gate
was removed, or because it is now locked to a value the user did not set.

Both are read from the feature list Kubernetes maintains for each release,
`test/compatibility_lifecycle/reference/versioned_feature_list.yaml`.
That list does not cover every gate kube-apiserver accepts (the client-go
ones are missing), so it cannot tell whether a gate exists, only what
happened to the ones it lists.

Usage: generate.py <from version> <to version>, e.g. generate.py 1.33.7 1.36.5
"""

import sys
import urllib.request

import yaml

FEATURE_LIST_URL = (
    "https://raw.githubusercontent.com/kubernetes/kubernetes/v{version}/"
    "test/compatibility_lifecycle/reference/versioned_feature_list.yaml"
)


def _minor(version):
    return tuple(int(part) for part in version.split(".")[:2])


def load_gates(version):
    """Return the spec of each gate, as it stands in `version`"""
    with urllib.request.urlopen(FEATURE_LIST_URL.format(version=version)) as resp:
        feature_list = yaml.safe_load(resp)

    gates = {}
    for gate in feature_list:
        specs = [
            spec
            for spec in gate["versionedSpecs"]
            if _minor(spec["version"]) <= _minor(version)
        ]
        if specs:
            gates[gate["name"]] = max(specs, key=lambda spec: _minor(spec["version"]))
    return gates


def main(from_version, to_version):
    old_gates = load_gates(from_version)
    new_gates = load_gates(to_version)

    removed = sorted(set(old_gates) - set(new_gates), key=str.lower)
    locked = sorted(
        (name for name, spec in new_gates.items() if spec["lockToDefault"]),
        key=str.lower,
    )

    print(
        f"# Generated by tools/kube-feature-gates/generate.py {from_version} {to_version}"
    )
    print("KUBE_REMOVED_FEATURE_GATES = frozenset(")
    print("    [")
    for name in removed:
        print(f'        "{name}",')
    print("    ]")
    print(")")
    print("KUBE_LOCKED_FEATURE_GATES = {")
    for name in locked:
        print(f'    "{name}": {new_gates[name]["default"]},')
    print("}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(*sys.argv[1:])
