annotations:
  artifacthub.io/changes: |
    - Disable builtin ssl_session_cache
    - Print warning only instead of error if no IngressClass permission is available
    - Bump internal libraries versions
    - Fix documentations
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 1.0.4
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer
home: https://github.com/kubernetes/ingress-nginx
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
keywords:
- ingress
- nginx
kubeVersion: '>=1.19.0-0'
maintainers:
- name: ChiefAlexander
name: ingress-nginx
sources:
- https://github.com/kubernetes/ingress-nginx
type: application
version: 4.0.6
