annotations:
  artifacthub.io/changes: |
    - "add lint on chart before release (#9570)"
    - "ci: remove setup-helm step (#9404)"
    - "feat(helm): Optionally use cert-manager instead admission patch (#9279)"
    - "run helm release on main only and when the chart/value changes only (#9290)"
    - "Update Ingress-Nginx version controller-v1.6.4"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 1.6.4
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and
  load balancer
home: https://github.com/kubernetes/ingress-nginx
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
keywords:
- ingress
- nginx
kubeVersion: '>=1.20.0-0'
maintainers:
- name: rikatz
- name: strongjz
- name: tao12345666333
name: ingress-nginx
sources:
- https://github.com/kubernetes/ingress-nginx
version: 4.5.2
