@startuml(id=LoggingSystemContext)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

title MetalK8s Logging - System Context
caption An overview of the logging system in a MetalK8s cluster.

Person(1, "Admin", "A MetalK8s administrator.")
System(28, "Application Containers", "All containerized applications running in MetalK8s.")
System(2, "External Log Storage", "A customer-provided system for storing log data.")
System(30, "Kubernetes API", "The core API for a Kubernetes cluster.")
System(3, "MetalK8s Logging", "Tools and services for collecting, aggregating, searching and displaying log data.")
System(31, "MetalK8s Monitoring", "MetalK8s services for monitoring and alerting.")
System(29, "Systemd Services", "MetalK8s services running on each host as systemd units.")
Rel_D(1, 3, "Sends a LogQL query to", "")
Rel_D(1, 31, "Consumes alerts and dashboards from", "")
Rel_D(3, 1, "Returns log lines to", "")
Rel_D(3, 28, "Collects logs from", "")
Rel_D(3, 2, "Forwards logs to", "")
Rel_D(3, 30, "Reads configuration from, and enriches logs with", "")
Rel_D(3, 31, "Triggers alerts", "")
Rel_D(3, 29, "Collects logs from", "")
Rel_D(31, 3, "Reads logs from", "")
@enduml