# List of Prometheus rules that will be dropped from the
# prometheus-operator charts at render time.
node-exporter:
  - NodeFilesystemSpaceFillingUp
  - NodeFilesystemAlmostOutOfSpace
  - NodeFilesystemFilesFillingUp
  - NodeFilesystemAlmostOutOfFiles
  - NodeNetworkReceiveErrs
  - NodeNetworkTransmitErrs
  - NodeHighNumberConntrackEntriesUsed
  - NodeClockSkewDetected
  - NodeClockNotSynchronising
  - NodeRAIDDegraded
  - NodeRAIDDiskFailure
  - NodeTextFileCollectorScrapeError
  - NodeFileDescriptorLimit
