image:
  repository: '__image__(fluent-bit)'
  pullPolicy: IfNotPresent

existingConfigMap: fluent-bit

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "2020"
  prometheus.io/path: /api/v1/metrics/prometheus

resources: '__var__(fluent_bit.spec.deployment.resources)'

tolerations:
- key: node-role.kubernetes.io/bootstrap
  effect: NoSchedule
  operator: Exists
- key: node-role.kubernetes.io/etcd
  effect: NoSchedule
  operator: Exists
- key: node-role.kubernetes.io/infra
  effect: NoSchedule
  operator: Exists
- key: node-role.kubernetes.io/master
  effect: NoSchedule
  operator: Exists

# Extra volumes to scrape logs from
daemonSetVolumes:
# /run/fluent-bit is used for fluent-bit DB
- name: run
  hostPath:
    path: /run/fluent-bit
- name: varlog
  hostPath:
    path: /var/log
# /run/log is used to fetch journal logs
- name: runlog
  hostPath:
    path: /run/log

daemonSetVolumeMounts:
- name: run
  mountPath: /run/fluent-bit
- name: varlog
  mountPath: /var/log
  readOnly: true
- name: runlog
  mountPath: /run/log
  readOnly: true

serviceMonitor:
  enabled: true
  selector:
    metalk8s.scality.com/monitor: ''
