controller:
  allowSnippetAnnotations: true

  config:
    custom-http-errors: "403,404,500,503"

  image:
    digest: null
    repository: __image__(nginx-ingress-controller)

  hostPort:
    enabled: true

  ingressClassResource:
    default: true

  watchIngressWithoutClass: true

  admissionWebhooks:
    enabled: false

  kind: DaemonSet

  tolerations:
  - key: "node-role.kubernetes.io/bootstrap"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"

  service:
    type: ClusterIP

  extraArgs:
    default-backend-service: metalk8s-ui/metalk8s-ui
    default-ssl-certificate: "metalk8s-ingress/ingress-workload-plane-default-certificate"
    metrics-per-host: false

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        metalk8s.scality.com/monitor: ''

defaultBackend:
  enabled: false
  extraConfigMaps:
  - name: cis
    labels:
      type: hardening
    data:
      keep-alive: '10'
      hide-headers: 'Server,X-Powered-By'
      ssl-protocols: 'TLSv1.3'
      ssl-ciphers: 'ALL:!EXP:!NULL:!ADH:!LOW:!SSLv2:!SSLv3:!MD5:!RC4'
      enable-ocsp: 'true'
      client-header-timeout: '10'
      client-body-timeout: '10'
  - name: custom-404.html
    labels:
      type: custom-404
    data:
      custom-404.html: |
        <html>
        <head><title>Page Not Found</title></head>
        <body><h1>404 - Page Not Found</h1></body>
        </html>
