controller:
  allowSnippetAnnotations: true

  image:
    digest: null
    repository: '{%- endraw -%}{{ build_image_name(\"nginx-ingress-controller\", False) }}{%- raw -%}'

  hostPort:
    enabled: true

  ingressClassResource:
    default: true

  watchIngressWithoutClass: true

  admissionWebhooks:
    enabled: false

  kind: DaemonSet

  tolerations:
    - key: "node-role.kubernetes.io/bootstrap"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/infra"
      operator: "Exists"
      effect: "NoSchedule"

  service:
    type: ClusterIP

  extraArgs:
    default-backend-service: metalk8s-ui/metalk8s-ui
    default-ssl-certificate: "metalk8s-ingress/ingress-workload-plane-default-certificate"
    metrics-per-host: false

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        metalk8s.scality.com/monitor: ''

defaultBackend:
  enabled: false
