{
 "title": "Logs",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "logs", "query": "loki" },
   { "name": "logmetrics", "query": "prometheus" },
   { "name": "metrics", "query": "prometheus" },
   { "name": "podlogs", "label": "Pod Logs", "query": "Enabled,Disabled" },
   { "name": "systemlogs", "label": "System Logs", "query": "Enabled,Disabled" },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info, cluster)"
   },
   {
    "name": "node",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, node)"
   },
   {
    "name": "instance",
    "query": "label_values(kube_node_info{cluster=\"$cluster\", node=~\"$node\"}, instance)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{cluster=\"$cluster\", instance=~\"$instance\"}, namespace)"
   },
   {
    "name": "deployment",
    "query": "label_values(kube_deployment_created{cluster=\"$cluster\", instance=~\"$instance\", namespace=~\"$namespace\"}, deployment)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_container_info{cluster=\"$cluster\", instance=~\"$instance\", namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "query": "label_values(kube_pod_container_info{cluster=\"$cluster\", instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   },
   {
    "name": "hostname",
    "query": "label_values({cluster=\"$cluster\"}, hostname)"
   },
   {
    "name": "unit",
    "query": "label_values({cluster=\"$cluster\", hostname=~\"$hostname\"}, unit)"
   },
   { "name": "level", "query": "debug,info,warn,error" },
   { "name": "filter", "label": "LogQL Filter" }
  ]
 },
 "panels": [
  {
   "title": "goroutines",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{cluster=\"$cluster\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "gc duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{cluster=\"$cluster\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m]))",
     "legendFormat": "total"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{cluster=\"$cluster\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m]))",
     "legendFormat": "total"
    },
    {
     "expr": "rate(container_memory_usage_bytes{cluster=\"$cluster\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "working set",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "tx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "rx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "restarts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[30m]) > 0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=\"$cluster\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", hostname=~\"$podlogs\"} |~ \"$filter\"[$__interval]))",
     "legendFormat": "Pod Logs"
    },
    {
     "expr": "sum(count_over_time({cluster=\"$cluster\", hostname=~\"$hostname\", unit=~\"$unit\", node=~\"$systemlogs\"} |~ \"$filter\"[$__interval]))",
     "legendFormat": "System Logs"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", hostname=~\"$podlogs\"} |~ \"$filter\""
    },
    {
     "expr": "{cluster=\"$cluster\", hostname=~\"$hostname\", unit=~\"$unit\", node=~\"$systemlogs\"} |~ \"$filter\""
    }
   ]
  }
 ]
}