image:
  repository: '__image__(loki)'

config:
  existingSecret: loki

persistence:
  enabled: true
  size: 10Gi
  storageClassName: metalk8s
  selector:
    matchLabels:
      app.kubernetes.io/name: loki

podAnnotations:
  # Override default checksum as we want to manage it with salt
  checksum/config: '__slot__:salt:metalk8s_kubernetes.get_object_digest(kind="Secret", apiVersion="v1", namespace="metalk8s-logging", name="loki", path="data:loki.yaml")'

replicas: '__var__(loki.spec.deployment.replicas)'

tolerations:
  - key: "node-role.kubernetes.io/bootstrap"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"

serviceMonitor:
  enabled: true
  additionalLabels:
    metalk8s.scality.com/monitor: ''

extraPorts:
  - port: 7946
    protocol: TCP
    name: memberlist
    targetPort: memberlist
