# permissions for end users to edit volumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: volume-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: storage-operator
    app.kubernetes.io/part-of: storage-operator
    app.kubernetes.io/managed-by: kustomize
  name: volume-editor-role
rules:
- apiGroups:
  - storage.metalk8s.scality.com
  resources:
  - volumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.metalk8s.scality.com
  resources:
  - volumes/status
  verbs:
  - get
