# permissions for end users to view clusterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterconfig-viewer-role
rules:
- apiGroups:
  - metalk8s.scality.com
  resources:
  - clusterconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metalk8s.scality.com
  resources:
  - clusterconfigs/status
  verbs:
  - get
