# permissions for end users to view clusterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterconfig-viewer-role
rules:
- apiGroups:
  - metalk8s.scality.com
  resources:
  - clusterconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metalk8s.scality.com
  resources:
  - clusterconfigs/status
  verbs:
  - get
