# permissions for end users to view virtualippools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualippool-viewer-role
rules:
- apiGroups:
  - metalk8s.scality.com
  resources:
  - virtualippools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metalk8s.scality.com
  resources:
  - virtualippools/status
  verbs:
  - get
