# permissions for end users to edit virtualippools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualippool-editor-role
rules:
- apiGroups:
  - metalk8s.scality.com
  resources:
  - virtualippools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metalk8s.scality.com
  resources:
  - virtualippools/status
  verbs:
  - get
