---
apiVersion: v1
kind: Pod
metadata:
  name: build-pod
spec:
  initContainers:
    - name: workaround
      image: k8s.gcr.io/build-image/debian-iptables-amd64:buster-v1.6.7
      command:
        - sh
        - -c
        - "iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu"
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
        privileged: true
  containers:
    - name: build-worker
      image: {{ images['docker-builder'] }}
      command: ["/bin/sh"]
      args: ["-c", "buildbot-worker create-worker . ${BUILDMASTER}:${BUILDMASTER_PORT} ${WORKERNAME} ${WORKERPASS} && buildbot-worker start --nodaemon"]
      resources:
        requests:
          # Most of our build steps run in containers, hence to run concurrent
          # builds, we need to allocate CPUs to the subsystem running Docker,
          # rather than to the environment in which `doit` is merely executed.
          # There's a limit of 4 CPUs, so we assign one to `doit`, and 3 to
          # Docker.
          cpu: "1"
          memory: 4Gi
        limits:
          cpu: "1"
          memory: 4Gi
      env:
        - name: DOCKER_HOST
          value: localhost:2375
      volumeMounts:
        - name: worker-workspace
          mountPath: /home/eve/workspace
    - name: platform-dind-daemon
      image: docker:20.10.8-dind
      resources:
        requests:
          cpu: "3"
          memory: 6Gi
        limits:
          cpu: "3"
          memory: 12Gi
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ''
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-storage
          mountPath: /var/lib/docker
        - name: worker-workspace
          mountPath: /home/eve/workspace
  volumes:
    # The two volumes below are used to avoid intensive IO in the Docker overlay
    # If extra performance is required, one could add `medium: Memory` to the
    # `emptyDir` dicts.
    # See https://docs.docker.com/storage/volumes/
    - name: docker-storage
      emptyDir: {}
    - name: worker-workspace
      emptyDir: {}
