apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: storage-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: storage-operator
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/bootstrap"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/infra"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
