name: "Prepare bastion"
description: "Prepare the bastion so to be ready to run tests"

inputs:
  BRANCH:
    description: "The git revision to checkout"
    required: false
    default: ${{ github.ref_name }}
  UI_DEPS:
    description: "Whether or not the bastion should be prepared to run UI tests"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Clone MetalK8s repository on Bastion
      uses: ./.github/actions/run-command-ssh
      with:
        NODE: bastion
        COMMAND: |
          if [ -d 'metalk8s' ]; then
            cd metalk8s && git checkout ${{ inputs.BRANCH }}
          else
            git clone --branch ${{ inputs.BRANCH }} \
              ${{ github.server_url }}/${{ github.repository }}
          fi
    - name: Install UI tests deps on Bastion
      if: inputs.UI_DEPS != 'false'
      uses: ./.github/actions/run-command-ssh
      with:
        NODE: bastion
        COMMAND: cd metalk8s && bash ui/cypress/requirements.sh
