name: "untaint node"
description: "Untaint a node"

inputs:
  NODE:
    description: "The node name to untaint"
    required: false
    default: "bootstrap"

runs:
  using: "composite"
  steps:
    - name: Untaint node ${{ inputs.NODE }}
      uses: ./.github/actions/run-command-ssh
      with:
        NODE: bootstrap
        COMMAND: >
          sudo kubectl --kubeconfig=/etc/kubernetes/admin.conf 
          patch node \"${{ inputs.NODE }}\" --patch '{
            \"metadata\": {\"labels\": {\"node-role.kubernetes.io/node\": \"\"}},
            \"spec\": {\"taints\": []}
          }'
