# -*- coding: utf-8 -*-
"""
Runner module handling MetalK8s cluster checks.
"""

import logging
import time

from salt.exceptions import CheckError

log = logging.getLogger(__name__)

__virtualname__ = "metalk8s_checks"

# A salt-master container replacement leaves the minions re-authenticating for
# a while, tolerate roughly two minutes of that before declaring one down.
MINIONS_PING_TIMEOUT = 10
MINIONS_PING_ATTEMPTS = 6
MINIONS_PING_INTERVAL = 10

# kube-apiserver refuses to start on a feature gate it no longer knows, or on one
# locked to the other value, and `kubernetes.apiServer.featureGates` is passed to
# it as is. Regenerate these on every Kubernetes bump, from the version the
# previous MetalK8s version ships to the one this release ships, see BUMPING.md.
# Generated by tools/kube-feature-gates/generate.py 1.34.7 1.36.5
KUBE_REMOVED_FEATURE_GATES = frozenset(
    [
        "AllowServiceLBStatusOnNonLB",
        "ComponentSLIs",
        "CPUCFSQuotaPeriod",
        "CronJobsScheduledAnnotation",
        "CSIMigrationPortworx",
        "DevicePluginCDIDevices",
        "ElasticIndexedJob",
        "HonorPVReclaimPolicy",
        "InPlacePodVerticalScalingAllocatedStatus",
        "InTreePluginPortworxUnregister",
        "LegacySidecarContainers",
        "LoadBalancerIPMode",
        "MemoryManager",
        "PodDisruptionConditions",
        "PodIndexLabel",
        "RuntimeClassInImageCriAPI",
        "ServiceTrafficDistribution",
        "SizeMemoryBackedVolumes",
        "StatefulSetAutoDeletePVC",
        "StatefulSetStartOrdinal",
        "StrictCostEnforcementForVAP",
        "StrictCostEnforcementForWebhooks",
        "StructuredAuthorizationConfiguration",
        "TopologyAwareHints",
        "UserNamespacesPodSecurityStandards",
        "WatchFromStorageWithoutResourceVersion",
    ]
)
KUBE_LOCKED_FEATURE_GATES = {
    "AggregatedDiscoveryRemoveBetaType": True,
    "AllowOverwriteTerminationGracePeriodSeconds": False,
    "AnonymousAuthConfigurableEndpoints": True,
    "AnyVolumeDataSource": True,
    "APIServerTracing": True,
    "AuthorizeNodeWithSelectors": True,
    "AuthorizeWithSelectors": True,
    "BtreeWatchCache": True,
    "ConsistentListFromCache": True,
    "CPUManagerPolicyOptions": True,
    "CRDValidationRatcheting": True,
    "CSIServiceAccountTokenSecrets": True,
    "CustomResourceFieldSelectors": True,
    "DeclarativeValidation": True,
    "DisableAllocatorDualWrite": True,
    "DisableNodeKubeProxyVersion": True,
    "DRAAdminAccess": True,
    "DynamicResourceAllocation": True,
    "ExecProbeTimeout": True,
    "ExternalServiceAccountTokenSigner": True,
    "GitRepoVolumeDriver": False,
    "ImageMaximumGCAge": True,
    "ImageVolume": True,
    "InPlacePodVerticalScaling": True,
    "JobBackoffLimitPerIndex": True,
    "JobManagedBy": True,
    "JobPodReplacementPolicy": True,
    "JobSuccessPolicy": True,
    "KubeletCgroupDriverFromCRI": True,
    "KubeletFineGrainedAuthz": True,
    "KubeletPodResourcesDynamicResources": True,
    "KubeletPodResourcesGet": True,
    "KubeletPSI": True,
    "KubeletTracing": True,
    "LogarithmicScaleDown": True,
    "MatchLabelKeysInPodAffinity": True,
    "MultiCIDRServiceAllocator": True,
    "MutableCSINodeAllocatableCount": True,
    "NFTablesProxyMode": True,
    "NodeInclusionPolicyInPodTopologySpread": True,
    "NodeLogQuery": True,
    "NodeSwap": True,
    "OrderedNamespaceDeletion": True,
    "PodLifecycleSleepAction": True,
    "PodLifecycleSleepActionAllowZero": True,
    "PodObservedGenerationTracking": True,
    "PodSchedulingReadiness": True,
    "PreferSameTrafficDistribution": True,
    "ProcMountType": True,
    "RecoverVolumeExpansionFailure": True,
    "RecursiveReadOnlyMounts": True,
    "RelaxedDNSSearchValidation": True,
    "RelaxedEnvironmentVariableValidation": True,
    "ResilientWatchCacheInitialization": True,
    "RetryGenerateName": True,
    "SchedulerQueueingHints": True,
    "SELinuxChangePolicy": True,
    "SELinuxMountReadWriteOncePod": True,
    "SeparateCacheWatchRPC": False,
    "SeparateTaintEvictionController": True,
    "ServiceAccountTokenJTI": True,
    "ServiceAccountTokenNodeBinding": True,
    "ServiceAccountTokenNodeBindingValidation": True,
    "ServiceAccountTokenPodNodeInfo": True,
    "SidecarContainers": True,
    "StreamingCollectionEncodingToJSON": True,
    "StreamingCollectionEncodingToProtobuf": True,
    "StructuredAuthenticationConfiguration": True,
    "SupplementalGroupsPolicy": True,
    "SystemdWatchdog": True,
    "TopologyManagerPolicyOptions": True,
    "UserNamespacesSupport": True,
    "VolumeAttributesClass": True,
    "WinDSR": True,
    "WinOverlay": True,
}


def __virtual__():
    return __virtualname__


def _handle_errors(errors, raises):
    """Simple helper to handle whether we should raise or not"""
    if not errors:
        return True

    if raises:
        raise CheckError("\n".join(errors))

    # Due to a bug in Salt run CLI, if a runner module raises the exit code
    # of the command is still 0.
    # In order to have an other exit code, today, we need to return a dict
    # with `retcode` key
    # See https://github.com/saltstack/salt/issues/61173
    return {"retcode": 1, "errors": errors}


def nodes(node_list=None, raises=True):
    """Check that all nodes are Ready

    Args:
        node_list (list, optional): List of node to check. Defaults to `pillar.metalk8s.nodes`.
        raises (bool, optional): Whether or not this function should raise. Defaults to True.

    Raises:
        CheckError: If 'raises' is True and some nodes are not ready

    Returns:
        dict or True: An error message or True if everything OK
    """
    errors = []

    if node_list is None:
        node_list = __pillar__["metalk8s"]["nodes"].keys()

    not_ready_nodes = {}
    for node_name in node_list:
        node_obj = __salt__["salt.cmd"](
            fun="metalk8s_kubernetes.get_object",
            kind="Node",
            apiVersion="v1",
            name=node_name,
        )

        condition = next(
            cond for cond in node_obj["status"]["conditions"] if cond["type"] == "Ready"
        )
        if condition["status"] != "True":
            not_ready_nodes.setdefault(condition["reason"], []).append(node_name)

    for reason, nodes_names in not_ready_nodes.items():
        errors.append(
            "Nodes '{}' are not ready - {}".format(  # pylint: disable=consider-using-f-string
                "', '".join(nodes_names), reason
            )
        )

    return _handle_errors(errors, raises)


def minions(
    minion_list=None,
    raises=True,
    timeout=MINIONS_PING_TIMEOUT,
    attempts=MINIONS_PING_ATTEMPTS,
    interval=MINIONS_PING_INTERVAL,
):
    """Check that all Salt minions are Ready

    A minion may legitimately miss a `test.ping` while it re-authenticates
    against a salt-master that has just been replaced, so a single unanswered
    probe is not enough to declare it down. Ping again, every `interval`
    seconds and up to `attempts` times, targeting only the minions we have yet
    to hear from.

    Args:
        minion_list (list, optional): List of Salt minion to check. Defaults to `pillar.metalk8s.nodes`.
        raises (bool, optional): Whether or not this function should raise. Defaults to True.
        timeout (int, optional): Timeout, in seconds, of a single `test.ping`. Defaults to 10.
        attempts (int, optional): How many times to ping the minions we did not hear from. Defaults to 6.
        interval (int, optional): Seconds to wait between two attempts. Defaults to 10.

    Raises:
        CheckError: If 'raises' is True and some Salt minions are not ready

    Returns:
        dict or True: An error message or True if everything OK
    """
    errors = []

    if minion_list is None:
        minion_list = __pillar__["metalk8s"]["nodes"].keys()

    attempts = max(attempts, 1)
    pending = list(minion_list)
    not_ready = []
    no_answer = []

    for attempt in range(1, attempts + 1):
        if attempt > 1:
            time.sleep(interval)

        ret = __salt__["salt.execute"](
            ",".join(pending), "test.ping", tgt_type="list", timeout=timeout
        )

        not_ready = [
            minion for minion, minion_ret in ret.items() if minion_ret is not True
        ]
        no_answer = sorted(set(pending) - set(ret.keys()))

        pending = not_ready + no_answer
        if not pending:
            break

        log.warning(
            "Salt minions '%s' did not answer 'test.ping' (attempt %d/%d)",
            "', '".join(pending),
            attempt,
            attempts,
        )

    for reason, minions_names in [
        ("are not ready", not_ready),
        ("did not answered", no_answer),
    ]:
        if minions_names:
            errors.append(
                "Salt minions '{}' {}".format(  # pylint: disable=consider-using-f-string
                    "', '".join(minions_names), reason
                )
            )

    return _handle_errors(errors, raises)


def _parse_feature_gate_value(value):
    """Parse a feature gate value the way kube-apiserver does (Go `ParseBool`)

    Returns None if the value is not a boolean: kube-apiserver refuses it
    whatever its version, so it is not an upgrade issue.
    """
    if isinstance(value, bool):
        return value
    if str(value) in ("1", "t", "T", "true", "TRUE", "True"):
        return True
    if str(value) in ("0", "f", "F", "false", "FALSE", "False"):
        return False
    return None


def _apiserver_feature_gates_errors(feature_gates):
    """List the feature gates kube-apiserver would refuse after the upgrade"""
    errors = []

    for name, value in sorted((feature_gates or {}).items()):
        if name in KUBE_REMOVED_FEATURE_GATES:
            errors.append(
                f"kube-apiserver feature gate '{name}' was removed from Kubernetes, "
                "remove it from 'kubernetes.apiServer.featureGates' in the "
                "Bootstrap configuration before upgrading"
            )
            continue

        locked_value = KUBE_LOCKED_FEATURE_GATES.get(name)
        if locked_value is None:
            continue
        if _parse_feature_gate_value(value) not in (None, locked_value):
            errors.append(
                f"kube-apiserver feature gate '{name}' is locked to "
                f"{str(locked_value).lower()} in Kubernetes, remove it from "
                "'kubernetes.apiServer.featureGates' in the Bootstrap "
                "configuration before upgrading"
            )

    return errors


def upgrade(dest_version, saltenv, raises=True):
    """Check that we can start MetalK8s cluster upgrade

    Args:
        dest_version (string): Destination version for upgrade
        saltenv (string): Salt environment that will be used for upgrade
        raises (bool, optional): Whether or not this function should raise. Defaults to True.

    Raises:
        CheckError: If 'raises' is True and some upgrade conditions are not met

    Returns:
        dict or True: An error message or True if everything OK
    """
    errors = []

    # NOTE: We use `get_from_map` as we want also defaults from `map.jinja`
    # to be merged
    metalk8s_pillar = __salt__["salt.cmd"](
        "metalk8s.get_from_map", "metalk8s", saltenv=saltenv, with_pillar=True
    )

    # When upgrading the saltenv should be the "metalk8s-<destination version>"
    if saltenv != f"metalk8s-{dest_version}":
        errors.append(
            f"Invalid saltenv '{saltenv}' consider using 'metalk8s-{dest_version}'"
        )

    # A node whose deployment did not complete can only be recovered by resuming the
    # same upgrade: bringing it to another version would mean downgrading it, which
    # this orchestrate cannot do. Refuse any other destination instead of leaving the
    # cluster with nodes stuck in the version of the interrupted upgrade.
    interrupted = {}
    for node_name, node_info in metalk8s_pillar["nodes"].items():
        in_progress = node_info.get("version_in_progress")
        if in_progress and in_progress != dest_version:
            interrupted.setdefault(in_progress, []).append(node_name)

    for version, node_names in sorted(interrupted.items()):
        errors.append(
            f"A version change to {version} did not complete on "
            f"{', '.join(sorted(node_names))}. Resume it rather than upgrading to "
            f"{dest_version}, since moving those nodes to {dest_version} would be a "
            f"downgrade. If {version} is not an option, clear their "
            "metalk8s.scality.com/version-in-progress annotation first"
        )

    # Check that all nodes are in a supported upgrade path
    # We only support upgrade from one major version
    dest = dest_version.split(".")
    min_version = f"{int(dest[0]) - 1}.0.0"

    for node_name, node_info in metalk8s_pillar["nodes"].items():
        if (
            __salt__["salt.cmd"]("pkg.version_cmp", min_version, node_info["version"])
            == 1
        ):
            errors.append(
                "Unable to upgrade from more than 1 major version, Node "
                f"{node_name} is in {node_info['version']} and you try to upgrade "
                f"to {dest_version}"
            )
    # The new kube-apiserver fails to start if a configured feature gate was
    # removed or locked. Check the gates now, so the upgrade stops before it
    # changes anything on the cluster.
    errors.extend(
        _apiserver_feature_gates_errors(
            __pillar__.get("kubernetes", {}).get("apiServer", {}).get("featureGates")
        )
    )

    nodes_ready = nodes(node_list=metalk8s_pillar["nodes"].keys(), raises=False)
    if nodes_ready is not True:
        errors.extend(nodes_ready["errors"])

    minions_ready = minions(minion_list=metalk8s_pillar["nodes"].keys(), raises=False)
    if minions_ready is not True:
        errors.extend(minions_ready["errors"])

    return _handle_errors(errors, raises)


def downgrade(dest_version, saltenv, raises=True, bypass_disable=False):
    """Check that we can start MetalK8s cluster downgrade

    Args:
        dest_version (string): Destination version for downgrade
        saltenv (string): Salt environment that will be used for downgrade
        raises (bool, optional): Whether or not this function should raise. Defaults to True.
        bypass_disable (bool, optional): Force downgrade if the downgrade path is not supported. Default to False.

    Raises:
        CheckError: If 'raises' is True and some downgrade conditions are not met

    Returns:
        dict or True: An error message or True if everything OK
    """
    errors = []

    # NOTE: We use `get_from_map` as we want also defaults from `map.jinja`
    # to be merged
    metalk8s_pillar = __salt__["salt.cmd"](
        "metalk8s.get_from_map", "metalk8s", saltenv=saltenv, with_pillar=True
    )

    # Check that all nodes are in a supported downgrade path
    # We only support downgrade from one major version
    dest = dest_version.split(".")
    max_version = f"{int(dest[0]) + 2}.0.0"

    newest_node_version = None

    for node_name, node_info in metalk8s_pillar["nodes"].items():
        if (
            newest_node_version is None
            or __salt__["salt.cmd"](
                "pkg.version_cmp", node_info["version"], newest_node_version
            )
            == 1
        ):
            newest_node_version = node_info["version"]

        if (
            __salt__["salt.cmd"]("pkg.version_cmp", max_version, node_info["version"])
            != 1
        ):
            errors.append(
                "Unable to downgrade from more than 1 major version, Node "
                f"{node_name} is in {node_info['version']} and you try to downgrade "
                f"to {dest_version}"
            )

    # Check that downgrade major version is supported
    if not bypass_disable and not metalk8s_pillar["downgrade"]["enabled"]:
        dest_major_version = dest[0]
        newest_node_major_version = newest_node_version.rsplit(".")[0]
        if dest_major_version != newest_node_major_version:
            errors.append(
                f"Downgrade is not supported from {newest_node_major_version} "
                f"to {dest_major_version} (see "
                f"https://github.com/scality/metalk8s/releases/tag/{newest_node_major_version}.0.0"
                " for details)"
            )

    # When downgrading the saltenv should be at least the newest node version
    if (
        __salt__["salt.cmd"](
            "pkg.version_cmp", saltenv.replace("metalk8s-", ""), newest_node_version
        )
        == -1
    ):
        errors.append(
            f"Invalid saltenv '{saltenv}' consider using at least 'metalk8s-{newest_node_version}'"
        )

    nodes_ready = nodes(node_list=metalk8s_pillar["nodes"].keys(), raises=False)
    if nodes_ready is not True:
        errors.extend(nodes_ready["errors"])

    minions_ready = minions(minion_list=metalk8s_pillar["nodes"].keys(), raises=False)
    if minions_ready is not True:
        errors.extend(minions_ready["errors"])

    return _handle_errors(errors, raises)
