# Simple NO AUTHENTICATION example
apiVersion: addons.metalk8s.scality.com
kind: AlertmanagerConfig
spec:
  notification:
    config:
      route:
        routes:
          - group_by:
              - ...
            matchers:
              - severity !~ \"info|none\"
            receiver: default
            continue: true
      receivers:
        - name: default
          email_configs:
            - smarthost: smtp4dev.default.svc.cluster.local:25
              require_tls: true
              from: lion@scality.com
              to: Renard <renard@scality.com>, Chat <chat@scality.com>, Lapin <lapin@scality.com>
              send_resolved: true
              html: TEMPLATE DELETED
