version: "2"

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

settings:
  revive:
    rules:
      - name: comment-spacings

exclusions:
  rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll
