#!/bin/bash
# set -e
set -u
set -o pipefail

pushd "$(dirname ${BASH_SOURCE[0]})" > /dev/null
SCRIPTS_DIR="$(pwd)"
popd > /dev/null

if [ ! -d "${SCRIPTS_DIR}" ]; then
    echo "Expected scripts directory '${SCRIPTS_DIR}' to be a directory" > /dev/stderr
    exit 1
fi

PYTHON36=$(command -v python3.6)
if [ -z "${PYTHON36}" ]; then
    PYTHON36=$(command -v python36)
fi

PYTHON27=$(command -v python2.7)
if [ -z "${PYTHON27}" ]; then
    PYTHON27=$(command -v python27)
fi

if [ -z "${PYTHON36}" ]; then
    PYTHON="${PYTHON27}"
else
    PYTHON="${PYTHON36}"
fi

if [ ! -x "${PYTHON}" ]; then
    echo "No suitable Python interpreter (2.7 or 3.6) found" > /dev/stderr
    exit 1
else
    "${PYTHON}" -c "import sys; assert sys.version_info >= (2, 7, 9)" &> /dev/null
    if [ $? -ne 0 ]; then
        echo "Python version is too low, must be higher than 2.7.9" > /dev/stderr
        exit 1
    fi
fi

exec "${PYTHON}" -B -E - "${@}" << EOS
import sys
sys.path.insert(0, "${SCRIPTS_DIR}")

assert sys.argv[0] == "-"
sys.argv[0] = "${BASH_SOURCE[0]}"

import metalk8s_cli.command
metalk8s_cli.command.main()
EOS
