repo: github.com/scality/metalk8s/operator
domain: metalk8s.scality.com
operator_dir: operator

operator_sdk_version: v1.42.1
go_toolchain: go1.25.8
k8s_libs: v0.33.9

apis:
  - version: v1alpha1
    kind: ClusterConfig
    namespaced: false
  - version: v1alpha1
    kind: VirtualIPPool
    namespaced: true

backup_paths:
  - pkg/
  - version/
  - config/metalk8s/
  - api/
  - hack/
  - internal/controller/

image_placeholder: '{{ build_image_name("metalk8s-operator") }}'

extra_commands:
  - ["make", "metalk8s"]
