name: "Certificates tests"
description: "Tests certificates expiration"

runs:
  using: "composite"
  steps:
    - name: "Retrieve MetalK8s mountpoint"
      id: metalk8s_mountpoint
      uses: ./.github/actions/retrieve-mountpoint
    - name: Copy certificates expiration tests on bootstrap
      uses: ./.github/actions/copy-file-ssh
      with:
        SOURCE_FILE: tests/test-certificates-beacon.sh
    - name: Run certificates expiration tests
      uses: ./.github/actions/run-command-ssh
      with:
        COMMAND: >
          sudo ./test-certificates-beacon.sh ${{ steps.metalk8s_mountpoint.outputs.mountpoint }}
