namespace: metalk8s-registry-system

resources:
  - github.com/scality/metalk8s-registry-operator.git/config/default?ref=v0.0.1-alpha.4

images:
  - name: controller
    newName: '{% endraw -%}{{ build_image_name("metalk8s-registry-operator", False) }}{%- raw %}'
    newTag: v0.0.1-alpha.4

patches:
  - path: deploy_patch.yaml
    target:
      kind: Deployment
  - path: delete_ns.yaml
