name: Start Cron jobs

on:
  # NOTE: Schedule is only run on the latest commit of the default branch,
  # so we need to schedule Cron Jobs for all branches here
  schedule:
    # Daily builds, scheduled before nightlies every weekday at 22:00
    - cron: "0 22 * * 1-5"

    # Run V 0 nightly every weekday at 01:00
    - cron: "0 1 * * 1-5"

    # Run V -1 nightly every weekday at 02:00
    - cron: "0 2 * * 1-5"

jobs:
  crons:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # Daily build jobs, needed to make sure we have at least one build
          # on latests commits of each branch. It is especially needed because
          # artifacts from builds expire after 2 weeks and nightly builds fail
          # current=132.0
          - name: "Build for MetalK8s 132.0"
            cron: "0 22 * * 1-5"
            branch: "development/132.0"
            workflow: "build.yaml"
          # old=131.0
          - name: "Build for MetalK8s 131.0"
            cron: "0 22 * * 1-5"
            branch: "development/131.0"
            workflow: "build.yaml"

          # Nightly jobs
          # these helper comments are needed by the dev branch workflow
          # please do not edit them unless you're changing the version as well
          # current=132.0
          - name: "Nightly for MetalK8s 132.0"
            cron: "0 1 * * 1-5"
            branch: "development/132.0"
            workflow: "nightly.yaml"
          # old=131.0
          - name: "Nightly for MetalK8s 131.0"
            cron: "0 2 * * 1-5"
            branch: "development/131.0"
            workflow: "nightly.yaml"
    steps:
      - name: Checkout
        if: github.event.schedule == matrix.cron
        uses: actions/checkout@v6
      - name: "Smart trigger for ${{ matrix.name }}"
        if: github.event.schedule == matrix.cron
        uses: scality/actions/actions-nightly-trigger@1.17.0
        with:
          branch: ${{ matrix.branch }}
          workflow: ${{ matrix.workflow }}
          access_token: ${{ secrets.GIT_ACCESS_TOKEN }}
