name: "delete old VMs in OpenStack"

on:
  workflow_dispatch:
  schedule:
    # Run it every 6 hours
    - cron: '0 */6 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up old VMs in OpenStack
        uses: scality/actions/actions-cleanup-openstack-vms@1.10.0
        with:
          AUTH_URL: ${{ secrets.OVH_AUTH_URL }}
          AGE_HOURS: 6
          REGION: ${{ secrets.OVH_REGION }}
          USERNAME: ${{secrets.OVH_USERNAME }}
          PASSWORD: ${{ secrets.OVH_PASSWORD }}
          PROJECT_NAME: ${{ secrets.OVH_PROJECT_NAME }}
          PROJECT_ID: ${{ secrets.OVH_PROJECT_ID }}
