---
name: dependency review

on:
  pull_request:
    branches: [development/*, stabilization/*, hotfix/*]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
