name: E2E Tests

on:
  workflow_call:
    inputs:
      artifacts-url:
        description: "Artifacts URL"
        required: true
        type: string
      nodes-count:
        description: "Number of extra node to spawn for multi-node"
        required: false
        type: number
        default: 1
      install-solution:
        description: "Whether or not the tests solution should be installed"
        required: false
        type: boolean
        default: false
      generate-snapshots:
        description: "Whether or not snapshots should be generated at the end"
        required: false
        type: boolean
        default: false
    secrets:
      ARTIFACTS_USER:
        required: true
      ARTIFACTS_PASSWORD:
        required: true
      OVH_AUTH_URL:
        required: true
      OVH_USERNAME:
        required: true
      OVH_PASSWORD:
        required: true
      OVH_REGION:
        required: true

  workflow_dispatch:
    inputs:
      artifacts-url:
        description: "Artifacts URL"
        required: true
        type: string
      nodes-count:
        description: "Number of extra node to spawn for multi-node"
        required: false
        type: string
        default: "1"
      install-solution:
        description: "Whether or not the tests solution should be installed"
        required: false
        type: boolean
        default: false
      generate-snapshots:
        description: "Whether or not snapshots should be generated at the end"
        required: false
        type: boolean
        default: false

env:
  CLOUD: "ovh"
  TERRAFORM_VERSION: "1.3.6"
  TERRAFORM_SNAPSHOT_TAG: "0.9.0"
  SOLUTION_ENV_NAME: "example-environment"
  SOLUTION_NAME: "example-solution"
  SOLUTION_VERSION: "1.0.2"
  SOLUTION_BASE_URL: "https://github.com/scality/metalk8s-solution-example/releases/download"

jobs:
  single-node-install:
    runs-on: [self-hosted, centos7, large]
    env:
      NAME: single-node
      SSH_PRIVATE_KEY: "~/.ssh/terraform"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: sudo yum install -y isomd5sum

     ## Spawn {{{
      - name: Export environment variables for accessing ${{ env.CLOUD }}
        uses: ./.github/actions/export-cloud-env
        with:
          CLOUD: ${{ env.CLOUD }}
          # Pass all "cloud access" secrets, the action will know which ones to export
          OVH_AUTH_URL: ${{ secrets.OVH_AUTH_URL }}
          OVH_USERNAME: ${{secrets.OVH_USERNAME }}
          OVH_PASSWORD: ${{ secrets.OVH_PASSWORD }}
          OVH_REGION: ${{ secrets.OVH_REGION }}
      - name: Spawn cluster with Terraform
        uses: ./.github/actions/spawn-cluster
        with:
          # Parameters
          CLOUD: ${{ env.CLOUD }}
          NAME: ${{ env.NAME }}
          NODES_COUNT: 0
          TERRAFORM_VERSION: ${{ env.TERRAFORM_VERSION }}
          TERRAFORM_SNAPSHOT_TAG: ${{ env.TERRAFORM_SNAPSHOT_TAG }}
          # Secrets
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
      - name: Save Terraform context
        if: always()
        uses: ./.github/actions/save-terraform-context
        with:
          NAME: ${{ env.NAME }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
      - name: Copy SSH config to current directory
        run: cp terraform-snapshot/terraform/ssh_config ./
      ## }}}

      # Install {{{
      - name: Get MetalK8s ISO
        uses: ./.github/actions/retrieve-iso
        with:
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
          ARTIFACTS_URL: ${{ inputs.artifacts-url }}
      - name: Copy MetalK8s ISO to the Bootstrap node
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "metalk8s.iso"
      - name: Generate Bootstrap config
        uses: ./.github/actions/generate-bootstrap
      - name: Mount MetalK8s ISO
        uses: ./.github/actions/mount-iso
      - name: Run Bootstrap
        uses: ./.github/actions/run-bootstrap
      - name: Provision volumes
        uses: ./.github/actions/provision-volumes
      - name: Untaint bootstrap node
        uses: ./.github/actions/untaint
      # }}}

      # Install solutions (if enabled) {{{
      - name: Get Solution ISO
        if: inputs.install-solution
        id: solution
        uses: ./.github/actions/retrieve-solution-iso
        with:
          base-url: ${{ env.SOLUTION_BASE_URL }}
          name: ${{ env.SOLUTION_NAME }}
          version: ${{ env.SOLUTION_VERSION }}
      - name: Copy Solution ISO to the Bootstrap node
        if: inputs.install-solution
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "${{ steps.solution.outputs.filename }}"
      - name: Deploy the Solution
        if: inputs.install-solution
        uses: ./.github/actions/deploy-solution
        with:
          path: ${{ steps.solution.outputs.filename }}
          name: ${{ env.SOLUTION_NAME }}
          version: ${{ env.SOLUTION_VERSION }}
          env-name: ${{ env.SOLUTION_ENV_NAME }}
      # }}}

      # Tests {{{
      - name: Wait for pods to stabilize
        uses: ./.github/actions/wait-pod-stable
      - name: Prepare bastion to run tests
        uses: ./.github/actions/prepare-bastion
        with:
          UI_DEPS: "true"
      - name: Run tests from Bastion
        uses: ./.github/actions/bastion-tests
      - name: Run UI tests from Bastion
        uses: ./.github/actions/bastion-ui-tests
      # }}}

      - name: Generate and Collect sosreport
        if: always()
        uses: ./.github/actions/sosreport-logs

      # Generate snapshots (if enabled) {{{
      - name: Retrieve product.txt from artifacts
        if: inputs.generate-snapshots
        run: >
          curl --fail -LO -u ${{ secrets.ARTIFACTS_USER }}:${{ secrets.ARTIFACTS_PASSWORD }}
          ${{ inputs.artifacts-url }}/product.txt
      - name: Get full MetalK8s version
        if: inputs.generate-snapshots
        run: |
          source product.txt
          echo "METALK8S_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Generate snapshot
        if: inputs.generate-snapshots
        uses: ./.github/actions/generate-snapshots
        with:
          snapshot-name: "metalk8s-${{ env.METALK8S_VERSION }}-rocky-8-single node"
          cloud: ${{ env.CLOUD }}
          nodes-count: 0
      # }}}

      - name: Upload artifacts
        if: always()
        uses: scality/action-artifacts@v3
        with:
          method: upload
          url: https://artifacts.scality.net
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          source: artifacts
      - name: debug
        if: failure()
        run: sleep 3600

  multi-node-install:
    runs-on: [self-hosted, centos7, large]
    env:
      NAME: multi-nodes
      SSH_PRIVATE_KEY: "~/.ssh/terraform"
      NODES_COUNT: ${{ inputs.nodes-count }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: sudo yum install -y isomd5sum

     ## Spawn {{{
      - name: Export environment variables for accessing ${{ env.CLOUD }}
        uses: ./.github/actions/export-cloud-env
        with:
          CLOUD: ${{ env.CLOUD }}
          # Pass all "cloud access" secrets, the action will know which ones to export
          OVH_AUTH_URL: ${{ secrets.OVH_AUTH_URL }}
          OVH_USERNAME: ${{secrets.OVH_USERNAME }}
          OVH_PASSWORD: ${{ secrets.OVH_PASSWORD }}
          OVH_REGION: ${{ secrets.OVH_REGION }}
      - name: Spawn cluster with Terraform
        uses: ./.github/actions/spawn-cluster
        with:
          # Parameters
          CLOUD: ${{ env.CLOUD }}
          NAME: ${{ env.NAME }}
          NODES_COUNT: ${{ env.NODES_COUNT }}
          TERRAFORM_VERSION: ${{ env.TERRAFORM_VERSION }}
          TERRAFORM_SNAPSHOT_TAG: ${{ env.TERRAFORM_SNAPSHOT_TAG }}
          # Secrets
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
      - name: Save Terraform context
        if: always()
        uses: ./.github/actions/save-terraform-context
        with:
          NAME: ${{ env.NAME }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
      - name: Copy SSH config to current directory
        run: cp terraform-snapshot/terraform/ssh_config ./
      ## }}}

      # Install {{{
      - name: Get MetalK8s ISO
        uses: ./.github/actions/retrieve-iso
        with:
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
          ARTIFACTS_URL: ${{ inputs.artifacts-url }}
      - name: Copy MetalK8s ISO to the Bootstrap node
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "metalk8s.iso"
      - name: Generate Bootstrap config
        uses: ./.github/actions/generate-bootstrap
        with:
          HARD_ANTIAFINITY: "true"
      - name: Mount MetalK8s ISO
        uses: ./.github/actions/mount-iso
      - name: Run Bootstrap
        uses: ./.github/actions/run-bootstrap
      - name: Prepare bastion to run tests
        uses: ./.github/actions/prepare-bastion
      - name: Prepare expansion
        uses: ./.github/actions/prepare-expansion
      - name: Wait for pods to stabilize before expansion
        uses: ./.github/actions/wait-pod-stable
      - name: Run expansion tests from Bastion
        uses: ./.github/actions/bastion-tests
        with:
          PYTEST_FILTERS: "install and ci and multinodes and not node$((${{ env.NODES_COUNT }} + 1))"
      - name: Provision volumes
        uses: ./.github/actions/provision-volumes
        with:
          NODE: "node-1"
      # }}}

      # Install solutions (if enabled) {{{
      - name: Untaint bootstrap node
        if: inputs.install-solution
        uses: ./.github/actions/untaint
      - name: Get Solution ISO
        if: inputs.install-solution
        id: solution
        uses: ./.github/actions/retrieve-solution-iso
        with:
          base-url: ${{ env.SOLUTION_BASE_URL }}
          name: ${{ env.SOLUTION_NAME }}
          version: ${{ env.SOLUTION_VERSION }}
      - name: Copy Solution ISO to the Bootstrap node
        if: inputs.install-solution
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "${{ steps.solution.outputs.filename }}"
      - name: Deploy the Solution
        if: inputs.install-solution
        uses: ./.github/actions/deploy-solution
        with:
          path: ${{ steps.solution.outputs.filename }}
          name: ${{ env.SOLUTION_NAME }}
          version: ${{ env.SOLUTION_VERSION }}
          env-name: ${{ env.SOLUTION_ENV_NAME }}
      # }}}

      # Tests {{{
      - name: Copy MetalK8s ISO to the node-1
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "metalk8s.iso"
          NODE_TO: "node-1"
      - name: Copy Solution ISO to the node-1
        if: inputs.install-solution
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "${{ steps.solution.outputs.filename }}"
          NODE_TO: "node-1"
      - name: Wait for pods to stabilize
        uses: ./.github/actions/wait-pod-stable
      - name: Run tests from Bastion
        uses: ./.github/actions/bastion-tests
        with:
          PYTEST_FILTERS: "post and ci and not slow"
      # }}}

      - name: Generate and Collect sosreport
        if: always()
        uses: ./.github/actions/sosreport-logs
        with:
          NODES_COUNT: "${{ env.NODES_COUNT }}"

      # Generate snapshots (if enabled) {{{
      - name: Retrieve product.txt from artifacts
        if: inputs.generate-snapshots
        run: >
          curl --fail -LO -u ${{ secrets.ARTIFACTS_USER }}:${{ secrets.ARTIFACTS_PASSWORD }}
          ${{ inputs.artifacts-url }}/product.txt
      - name: Get full MetalK8s version and total number of nodes
        if: inputs.generate-snapshots
        run: |
          source product.txt
          echo "METALK8S_VERSION=$VERSION" >> $GITHUB_ENV
          echo "TOTAL_NB_NODES=$((${{ env.NODES_COUNT }} + 1))" >> $GITHUB_ENV
      - name: Generate snapshot
        if: inputs.generate-snapshots
        uses: ./.github/actions/generate-snapshots
        with:
          snapshot-name: "metalk8s-${{ env.METALK8S_VERSION }}-rocky-8-${{ env.TOTAL_NB_NODES }} nodes"
          cloud: ${{ env.CLOUD }}
          nodes-count: "${{ env.NODES_COUNT }}"
      # }}}

      - name: Upload artifacts
        if: always()
        uses: scality/action-artifacts@v3
        with:
          method: upload
          url: https://artifacts.scality.net
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          source: artifacts
      - name: debug
        if: failure()
        run: sleep 3600

  destroy-single-node-cluster:
    needs:
      - single-node-install
    runs-on: [self-hosted, centos7, large]
    if: always()
    env:
      NAME: single-node
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get artifacts URL
        uses: scality/action-artifacts@v3
        id: artifacts
        with:
          method: setup
          url: https://artifacts.scality.net
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
      - name: Export environment variables for accessing ${{ env.CLOUD }}
        uses: ./.github/actions/export-cloud-env
        with:
          CLOUD: ${{ env.CLOUD }}
          # Pass all "cloud access" secrets, the action will know which ones to export
          OVH_AUTH_URL: ${{ secrets.OVH_AUTH_URL }}
          OVH_USERNAME: ${{secrets.OVH_USERNAME }}
          OVH_PASSWORD: ${{ secrets.OVH_PASSWORD }}
          OVH_REGION: ${{ secrets.OVH_REGION }}
      - name: Destroy cluster with Terraform
        uses: ./.github/actions/destroy-cluster
        with:
          # Parameters
          CLOUD: ${{ env.CLOUD }}
          TERRAFORM_SNAPSHOT_TAG: ${{ env.TERRAFORM_SNAPSHOT_TAG }}
          TERRAFORM_VERSION: ${{ env.TERRAFORM_VERSION }}
          ARTIFACTS_URL: ${{ steps.artifacts.outputs.link }}
          NAME: ${{ env.NAME }}
          # Secrets
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}

  destroy-multi-node-cluster:
    needs:
      - multi-node-install
    runs-on: [self-hosted, centos7, large]
    if: always()
    env:
      NAME: multi-nodes
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get artifacts URL
        uses: scality/action-artifacts@v3
        id: artifacts
        with:
          method: setup
          url: https://artifacts.scality.net
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
      - name: Export environment variables for accessing ${{ env.CLOUD }}
        uses: ./.github/actions/export-cloud-env
        with:
          CLOUD: ${{ env.CLOUD }}
          # Pass all "cloud access" secrets, the action will know which ones to export
          OVH_AUTH_URL: ${{ secrets.OVH_AUTH_URL }}
          OVH_USERNAME: ${{secrets.OVH_USERNAME }}
          OVH_PASSWORD: ${{ secrets.OVH_PASSWORD }}
          OVH_REGION: ${{ secrets.OVH_REGION }}
      - name: Destroy cluster with Terraform
        uses: ./.github/actions/destroy-cluster
        with:
          # Parameters
          CLOUD: ${{ env.CLOUD }}
          TERRAFORM_SNAPSHOT_TAG: ${{ env.TERRAFORM_SNAPSHOT_TAG }}
          TERRAFORM_VERSION: ${{ env.TERRAFORM_VERSION }}
          ARTIFACTS_URL: ${{ steps.artifacts.outputs.link }}
          NAME: ${{ env.NAME }}
          # Secrets
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
