name: Multi Node test

on:
  workflow_call:
    inputs:
      artifacts-url:
        description: "Artifacts URL"
        required: true
        type: string

      # Machine setup
      os:
        description: "The OS to use"
        required: false
        type: string
        default: "rocky-8"
      nodes-count:
        description: "Number of extra node to spawn"
        required: false
        type: number
        default: 1

      # Steps to run
      install-solution:
        description: "Whether or not the tests solution should be installed"
        required: false
        type: boolean
        default: false
      generate-snapshots:
        description: "Whether or not snapshots should be generated at the end"
        required: false
        type: boolean
        default: false

      # Solution information
      solution-name:
        description: "The solution name to install"
        required: false
        type: string
        default: "example-solution"
      solution-version:
        description: "The solution version to install"
        required: false
        type: string
        default: "1.0.2"
      solution-base-url:
        description: "The URL to download the solution"
        required: false
        type: string
        default: "https://github.com/scality/metalk8s-solution-example/releases/download"
      solution-env-name:
        description: "The solution environment name"
        required: false
        type: string
        default: "example-environment"

env:
  NAME: multi-nodes-${{ inputs.os }}

jobs:
  multi-node:
    runs-on: [self-hosted, centos7, large]
    env:
      SSH_PRIVATE_KEY: "~/.ssh/terraform"
      NODES_COUNT: ${{ inputs.nodes-count }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: sudo yum install -y isomd5sum

     ## Spawn {{{
      - name: Export environment variables for accessing the cloud
        uses: ./.github/actions/export-cloud-env
        with:
          # Pass all "cloud access" secrets, the action will know which ones to export
          OVH_AUTH_URL: ${{ secrets.OVH_AUTH_URL }}
          OVH_USERNAME: ${{secrets.OVH_USERNAME }}
          OVH_PASSWORD: ${{ secrets.OVH_PASSWORD }}
          OVH_REGION: ${{ secrets.OVH_REGION }}
      - name: Spawn cluster with Terraform
        uses: ./.github/actions/spawn-cluster
        with:
          # Parameters
          OS: ${{ inputs.os }}
          NAME: ${{ env.NAME }}
          NODES_COUNT: ${{ env.NODES_COUNT }}
          # Secrets
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
      - name: Save Terraform context
        if: always()
        uses: ./.github/actions/save-terraform-context
        with:
          NAME: ${{ env.NAME }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
      - name: Copy SSH config to current directory
        run: cp terraform-snapshot/terraform/ssh_config ./
      ## }}}

      # Install {{{
      - name: Get MetalK8s ISO
        uses: ./.github/actions/retrieve-iso
        with:
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
          ARTIFACTS_URL: ${{ inputs.artifacts-url }}
      - name: Copy MetalK8s ISO to the Bootstrap node
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "metalk8s.iso"
      - name: Generate Bootstrap config
        uses: ./.github/actions/generate-bootstrap
        with:
          HARD_ANTIAFINITY: "true"
      - name: Mount MetalK8s ISO
        uses: ./.github/actions/mount-iso
      - name: Run Bootstrap
        uses: ./.github/actions/run-bootstrap
      - name: Prepare bastion to run tests
        uses: ./.github/actions/prepare-bastion
      - name: Prepare expansion
        uses: ./.github/actions/prepare-expansion
      - name: Wait for pods to stabilize before expansion
        uses: ./.github/actions/wait-pod-stable
      - name: Run expansion tests from Bastion
        uses: ./.github/actions/bastion-tests
        with:
          PYTEST_FILTERS: "install and ci and multinodes and not node$((${{ env.NODES_COUNT }} + 1))"
      - name: Provision volumes
        uses: ./.github/actions/provision-volumes
        with:
          NODE: "node-1"
      # }}}

      # Install solutions (if enabled) {{{
      - name: Untaint bootstrap node
        if: inputs.install-solution
        uses: ./.github/actions/untaint
      - name: Get Solution ISO
        if: inputs.install-solution
        id: solution
        uses: ./.github/actions/retrieve-solution-iso
        with:
          base-url: ${{ inputs.solution-base-url }}
          name: ${{ inputs.solution-name }}
          version: ${{ inputs.solution-version }}
      - name: Copy Solution ISO to the Bootstrap node
        if: inputs.install-solution
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "${{ steps.solution.outputs.filename }}"
      - name: Deploy the Solution
        if: inputs.install-solution
        uses: ./.github/actions/deploy-solution
        with:
          path: ${{ steps.solution.outputs.filename }}
          name: ${{ inputs.solution-name }}
          version: ${{ inputs.solution-version }}
          env-name: ${{ inputs.solution-env-name }}
      # }}}

      # Tests {{{
      - name: Copy MetalK8s ISO to the node-1
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "metalk8s.iso"
          NODE_TO: "node-1"
      - name: Copy Solution ISO to the node-1
        if: inputs.install-solution
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "${{ steps.solution.outputs.filename }}"
          NODE_TO: "node-1"
      - name: Wait for pods to stabilize
        uses: ./.github/actions/wait-pod-stable
      - name: Run tests from Bastion
        uses: ./.github/actions/bastion-tests
        with:
          PYTEST_FILTERS: "post and ci and not slow"
      # }}}

      - name: Generate and Collect sosreport
        if: always()
        uses: ./.github/actions/sosreport-logs
        with:
          NODES_COUNT: "${{ env.NODES_COUNT }}"

      # Generate snapshots (if enabled) {{{
      - name: Retrieve product.txt from artifacts
        if: inputs.generate-snapshots
        run: >
          curl --fail -LO -u ${{ secrets.ARTIFACTS_USER }}:${{ secrets.ARTIFACTS_PASSWORD }}
          ${{ inputs.artifacts-url }}/product.txt
      - name: Get full MetalK8s version and total number of nodes
        if: inputs.generate-snapshots
        run: |
          source product.txt
          echo "METALK8S_VERSION=$VERSION" >> $GITHUB_ENV
          echo "TOTAL_NB_NODES=$((${{ env.NODES_COUNT }} + 1))" >> $GITHUB_ENV
      - name: Generate snapshot
        if: inputs.generate-snapshots
        uses: ./.github/actions/generate-snapshots
        with:
          snapshot-name: "metalk8s-${{ env.METALK8S_VERSION }}-${{ inputs.os }}-${{ env.TOTAL_NB_NODES }} nodes"
          nodes-count: "${{ env.NODES_COUNT }}"
      # }}}

      - name: Upload artifacts
        if: always()
        uses: scality/action-artifacts@v3
        with:
          method: upload
          url: https://artifacts.scality.net
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          source: artifacts
      - name: debug
        if: failure()
        run: sleep 3600

  destroy-multi-node-cluster:
    needs:
      - multi-node
    runs-on: [self-hosted, centos7, large]
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get artifacts URL
        uses: scality/action-artifacts@v3
        id: artifacts
        with:
          method: setup
          url: https://artifacts.scality.net
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
      - name: Export environment variables for accessing the cloud
        uses: ./.github/actions/export-cloud-env
        with:
          # Pass all "cloud access" secrets, the action will know which ones to export
          OVH_AUTH_URL: ${{ secrets.OVH_AUTH_URL }}
          OVH_USERNAME: ${{secrets.OVH_USERNAME }}
          OVH_PASSWORD: ${{ secrets.OVH_PASSWORD }}
          OVH_REGION: ${{ secrets.OVH_REGION }}
      - name: Destroy cluster with Terraform
        uses: ./.github/actions/destroy-cluster
        with:
          # Parameters
          ARTIFACTS_URL: ${{ steps.artifacts.outputs.link }}
          NAME: ${{ env.NAME }}
          # Secrets
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
