name: Multi Node test

on:
  workflow_call:
    inputs:
      artifacts-url:
        description: "Artifacts URL"
        required: true
        type: string

      # Machine setup
      name:
        description: "Override the name of the environment"
        required: false
        type: string
        default: ""
      os:
        description: "The OS to use"
        required: false
        type: string
        default: "rocky-8"
      nodes-count:
        description: "Number of extra node to spawn"
        required: false
        type: number
        default: 1

      # Steps to run
      install-solution:
        description: "Whether or not the tests solution should be installed"
        required: false
        type: boolean
        default: false
      generate-snapshots:
        description: "Whether or not snapshots should be generated at the end"
        required: false
        type: boolean
        default: false
      bootstrap-restore:
        description: "Whether or not bootstrap restore should be tested"
        required: false
        type: boolean
        default: false
      k8s-conformance:
        description: "Whether or not k8s conformance tests should be ran"
        required: false
        type: boolean
        default: false
      enable-debug-when-failure:
        description: "Whether or not debug when failure should be enabled or not"
        required: false
        type: boolean
        default: false

      # Solution information
      solution-name:
        description: "The solution name to install"
        required: false
        type: string
        default: "example-solution"
      solution-version:
        description: "The solution version to install"
        required: false
        type: string
        default: "1.0.2"
      solution-base-url:
        description: "The URL to download the solution"
        required: false
        type: string
        default: "https://github.com/scality/metalk8s-solution-example/releases/download"
      solution-env-name:
        description: "The solution environment name"
        required: false
        type: string
        default: "example-environment"

env:
  NAME: ${{ inputs.name || format('multi-nodes-{0}', inputs.os) }}

jobs:
  multi-node:
    # We need to use a large runner so that we have known runner IPs
    # It allows us to filter authorized IPs on the machines we spawn
    runs-on: ubuntu-22.04-4core
    env:
      SSH_PRIVATE_KEY: "~/.ssh/terraform"
      NODES_COUNT: ${{ inputs.nodes-count }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y isomd5sum jq
      - name: Retrieve product.txt from artifacts
        run: >
          curl --fail -LO -u ${{ secrets.ARTIFACTS_USER }}:${{ secrets.ARTIFACTS_PASSWORD }}
          ${{ inputs.artifacts-url }}/product.txt
      - name: Get full MetalK8s version
        run: |
          source product.txt
          echo "METALK8S_VERSION=$VERSION" >> $GITHUB_ENV
          echo "METALK8S_SHORT_VERSION=$SHORT_VERSION" >> $GITHUB_ENV

     ## Spawn {{{
      - name: Export environment variables for accessing the cloud
        uses: ./.github/actions/export-cloud-env
        with:
          # Pass all "cloud access" secrets, the action will know which ones to export
          OVH_AUTH_URL: ${{ secrets.OVH_AUTH_URL }}
          OVH_USERNAME: ${{secrets.OVH_USERNAME }}
          OVH_PASSWORD: ${{ secrets.OVH_PASSWORD }}
          OVH_REGION: ${{ secrets.OVH_REGION }}
      - name: Spawn cluster with Terraform
        uses: ./.github/actions/spawn-cluster
        with:
          # Parameters
          OS: ${{ inputs.os }}
          NAME: ${{ env.NAME }}
          NODES_COUNT: ${{ env.NODES_COUNT }}
          # Secrets
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
          AUTHORIZED_CIDRS: ${{ vars.AUTHORIZED_CIDRS }}
      - name: Save Terraform context
        if: always()
        uses: ./.github/actions/save-terraform-context
        with:
          NAME: ${{ env.NAME }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
      - name: Copy SSH config to current directory
        run: cp terraform-snapshot/terraform/ssh_config ./
      ## }}}

      # Install {{{
      - name: Get MetalK8s ISO
        uses: ./.github/actions/retrieve-iso
        with:
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
          ARTIFACTS_URL: ${{ inputs.artifacts-url }}
      - name: Copy MetalK8s ISO to the Bootstrap node
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "metalk8s.iso"
      - name: Generate Bootstrap config
        uses: ./.github/actions/generate-bootstrap
        with:
          HARD_ANTIAFINITY: "true"
      - name: Mount MetalK8s ISO
        uses: ./.github/actions/mount-iso
      - name: Prepare expansion
        uses: ./.github/actions/prepare-expansion
      - name: Run Bootstrap
        uses: ./.github/actions/run-bootstrap
      - name: Enable managed VIP for Control Plane Ingress
        uses: ./.github/actions/enable-cp-ingress-managed-vip
        with:
          metalk8s-version: ${{ env.METALK8S_VERSION }}
      - name: Prepare bastion to run tests
        uses: ./.github/actions/prepare-bastion
      - name: Wait for pods to stabilize before expansion
        uses: ./.github/actions/wait-pod-stable
      - name: Run expansion tests from Bastion
        uses: ./.github/actions/bastion-tests
        with:
          PYTEST_FILTERS: "install and ci and multinodes and not node$((${{ env.NODES_COUNT }} + 1))"
      - name: Provision volumes
        uses: ./.github/actions/provision-volumes
        with:
          NODE: "node-1"
      # }}}

      # Install solutions (if enabled) {{{
      - name: Untaint bootstrap node
        if: inputs.install-solution
        uses: ./.github/actions/untaint
      - name: Get Solution ISO
        if: inputs.install-solution
        id: solution
        uses: ./.github/actions/retrieve-solution-iso
        with:
          base-url: ${{ inputs.solution-base-url }}
          name: ${{ inputs.solution-name }}
          version: ${{ inputs.solution-version }}
      - name: Copy Solution ISO to the Bootstrap node
        if: inputs.install-solution
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "${{ steps.solution.outputs.filename }}"
      - name: Deploy the Solution
        if: inputs.install-solution
        uses: ./.github/actions/deploy-solution
        with:
          path: ${{ steps.solution.outputs.filename }}
          name: ${{ inputs.solution-name }}
          version: ${{ inputs.solution-version }}
          env-name: ${{ inputs.solution-env-name }}
      # }}}

      # Tests {{{
      - name: Copy MetalK8s ISO to the node-1
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "metalk8s.iso"
          NODE_TO: "node-1"
      - name: Copy Solution ISO to the node-1
        if: inputs.install-solution
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "${{ steps.solution.outputs.filename }}"
          NODE_TO: "node-1"
      - name: Wait for pods to stabilize
        uses: ./.github/actions/wait-pod-stable
      - name: Run tests from Bastion
        uses: ./.github/actions/bastion-tests
        with:
          PYTEST_FILTERS: "post and ci and not slow"
      # }}}

      # Bootstrap restore (if enabled) {{{
      - name: Retrieve latest Bootstrap backup
        if: inputs.bootstrap-restore
        id: backup
        uses: ./.github/actions/retrieve-backup
      - name: Destroy the Bootstrap node
        if: inputs.bootstrap-restore
        uses: ./.github/actions/destroy-cluster
        with:
          # Parameters
          NAME: ${{ env.NAME }}
          args: -target openstack_compute_instance_v2.bootstrap
          # Secrets
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
      - name: Save Terraform context after Bootstrap destroy
        if: inputs.bootstrap-restore
        uses: ./.github/actions/save-terraform-context
        with:
          NAME: ${{ env.NAME }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
      - name: Remove the Bootstrap node from the cluster
        if: inputs.bootstrap-restore
        uses: ./.github/actions/remove-node
      - name: Create a new bootstrap node
        if: inputs.bootstrap-restore
        uses: ./.github/actions/spawn-cluster
        with:
          # Parameters
          OS: ${{ inputs.os }}
          NAME: ${{ env.NAME }}
          NODES_COUNT: ${{ env.NODES_COUNT }}
          skip-prepare: "true"
          args: >-
            -refresh
            -target openstack_compute_instance_v2.bootstrap
            -target null_resource.copy_bastion_pub_to_bootstrap
            -target null_resource.ssh_config
          # Secrets
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
      - name: Save Terraform context after Bootstrap re-creation
        if: inputs.bootstrap-restore
        uses: ./.github/actions/save-terraform-context
        with:
          NAME: ${{ env.NAME }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
      - name: Copy the new SSH config to current directory
        if: inputs.bootstrap-restore
        run: cp terraform-snapshot/terraform/ssh_config ./
      - name: Copy the backup archive to the new Bootstrap node
        if: inputs.bootstrap-restore
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "${{ steps.backup.outputs.filename }}"
          DESTINATION_FILE: "/tmp/${{ steps.backup.outputs.filename }}"
      - name: Copy MetalK8s ISO to the new Bootstrap node
        if: inputs.bootstrap-restore
        uses: ./.github/actions/copy-file-ssh
        with:
          SOURCE_FILE: "metalk8s.iso"
      - name: Mount MetalK8s ISO on the new Bootstrap node
        if: inputs.bootstrap-restore
        id: mount-iso
        uses: ./.github/actions/mount-iso
      - name: Run restore tests from Bastion
        if: inputs.bootstrap-restore
        uses: ./.github/actions/bastion-tests
        with:
          PYTEST_FILTERS: "restore"
          BOOTSTRAP_BACKUP_ARCHIVE: "/tmp/${{ steps.backup.outputs.filename }}"
          # NOTE: We need to specify the mountpoint since it will not be
          # able to auto-discover it because the bootstrap node is down
          mountpoint: ${{ steps.mount-iso.outputs.mountpoint }}
      - name: Wait for pods to stabilize after restore
        if: inputs.bootstrap-restore
        uses: ./.github/actions/wait-pod-stable
      - name: Run tests from Bastion after restore
        if: inputs.bootstrap-restore
        uses: ./.github/actions/bastion-tests
        with:
          PYTEST_FILTERS: "post and ci and not slow"
      # }}}

      # Run k8s conformance tests (if enabled) {{{
      - name: Untaint bootstrap node for conformance tests
        if: inputs.k8s-conformance
        uses: ./.github/actions/untaint
      - name: Expose nodeport and portmap on every IPs
        if: inputs.k8s-conformance
        uses: ./.github/actions/run-command-ssh
        with:
          COMMAND: |
            sudo salt-call --local --retcode-passthrough state.single file.serialize /etc/metalk8s/bootstrap.yaml dataset='{"networks": {"nodeport": {"cidr": "0.0.0.0/0"}, "portmap": {"cidr": "0.0.0.0/0"}}}' merge_if_exists=True
            SALT_MASTER=\$(sudo crictl ps --label="io.kubernetes.container.name=salt-master" -q)
            sudo crictl exec \$SALT_MASTER salt-run state.sls metalk8s.kubernetes.kube-proxy.deployed saltenv=metalk8s-$METALK8S_VERSION
            sudo crictl exec \$SALT_MASTER salt-run state.sls metalk8s.kubernetes.cni.calico.deployed saltenv=metalk8s-$METALK8S_VERSION
            sudo crictl exec \$SALT_MASTER salt '*' state.sls metalk8s.addons.nginx-ingress.certs saltenv=metalk8s-$METALK8S_VERSION
      - name: Wait for pods to stabilize before conformance tests
        if: inputs.k8s-conformance
        uses: ./.github/actions/wait-pod-stable
      - name: Run the k8s conformance tests
        if: inputs.k8s-conformance
        uses: ./.github/actions/run-k8s-conformance
        with:
          metalk8s-short-version: "${{ env.METALK8S_SHORT_VERSION }}"
      # }}}

      - name: Generate and Collect sosreport
        if: always()
        uses: ./.github/actions/sosreport-logs
        with:
          NODES_COUNT: "${{ env.NODES_COUNT }}"

      ## Generate job result {{
      - name: Generate Job result
        if: always()
        uses: ./.github/actions/generate-job-result
        with:
          name: ${{ env.NAME }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
          GIT_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ## }}

      # Generate snapshots (if enabled) {{{
      - name: Get total number of nodes
        if: inputs.generate-snapshots
        run: |
          echo "TOTAL_NB_NODES=$((${{ env.NODES_COUNT }} + 1))" >> $GITHUB_ENV
      - name: Generate snapshot
        if: inputs.generate-snapshots
        uses: ./.github/actions/generate-snapshots
        with:
          snapshot-name: "metalk8s-${{ env.METALK8S_VERSION }}-${{ inputs.os }}-${{ env.TOTAL_NB_NODES }} nodes"
          nodes-count: "${{ env.NODES_COUNT }}"
      # }}}

      - name: Upload artifacts
        if: always()
        uses: scality/action-artifacts@v4
        with:
          method: upload
          url: https://artifacts.scality.net
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          source: artifacts
      - name: debug
        if: inputs.enable-debug-when-failure && failure()
        run: sleep 3600

  destroy-multi-node-cluster:
    needs:
      - multi-node
    # We need to use a large runner so that we have known runner IPs
    # It allows us to filter authorized IPs on the machines we spawn
    runs-on: ubuntu-22.04-4core
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get artifacts URL
        uses: scality/action-artifacts@v4
        id: artifacts
        with:
          method: setup
          url: https://artifacts.scality.net
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
      - name: Export environment variables for accessing the cloud
        uses: ./.github/actions/export-cloud-env
        with:
          # Pass all "cloud access" secrets, the action will know which ones to export
          OVH_AUTH_URL: ${{ secrets.OVH_AUTH_URL }}
          OVH_USERNAME: ${{secrets.OVH_USERNAME }}
          OVH_PASSWORD: ${{ secrets.OVH_PASSWORD }}
          OVH_REGION: ${{ secrets.OVH_REGION }}
      - name: Destroy cluster with Terraform
        uses: ./.github/actions/destroy-cluster
        with:
          # Parameters
          ARTIFACTS_URL: ${{ steps.artifacts.outputs.link }}
          NAME: ${{ env.NAME }}
          # Secrets
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
