name: Pre merge

concurrency:
  # This stops any build on a branch if a new commit is pushed on that branch
  # the second check is here to run each build when pushing on the branch `q/*`
  # in order for bert-e to merge any branch that passes the queue before waiting
  # for the entire queue to passe the build.
  # if the branch is 'q/*' then we append the commit sha to the concurrency group to make it unique.
  # this works because the '||' or condition will only evaluate the right side if the left side is false ;-)
  group: "tests-${{ github.ref_name }}-${{ ( !startsWith(github.ref_name, 'q/') || github.sha) }}"
  cancel-in-progress: true

on:
  push:
    branches:
      - "release/**"
      - "feature/**"
      - "improvement/**"
      - "hotfix/**"
      - "bugfix/**"
      - "documentation/**"
      - "user/**"
      - "dependabot/**"
      - "w/**"
      - "q/*/**"
      - "q/*"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  e2e-tests:
    needs:
      - build
    uses: ./.github/workflows/e2e-tests.yaml
    secrets: inherit
    with:
      artifact-url: ${{ needs.build.outputs.artifact-link }}

  write-final-failed-status:
    runs-on: ubuntu-20.04
    needs:
      - e2e-tests
    if: failure()
    steps:
      - name: write failure status
        run: |
          mkdir -p artifacts
          echo -n "FAILED" > artifacts/.final_status
      - name: Upload artifacts
        uses: scality/action-artifacts@v3
        with:
          method: upload
          url: https://artifacts.scality.net
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          source: artifacts

  write-final-success-status:
    runs-on: ubuntu-20.04
    needs:
      - e2e-tests
    if: success()
    steps:
      - name: write failure status
        run: |
          mkdir -p artifacts
          echo -n "SUCCESSFUL" > artifacts/.final_status
      - name: Upload artifacts
        uses: scality/action-artifacts@v3
        with:
          method: upload
          url: https://artifacts.scality.net
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          source: artifacts
