name: "Retrieve ISO"
description: "Retrieve MetalK8s ISO and checksum, check it and copy it to bootstrap"

inputs:
  ARTIFACTS_USER:
    description: "Username to get artifacts"
    required: true
  ARTIFACTS_PASSWORD:
    description: "Password to get artifacts"
    required: true
  ARTIFACT_URL:
    description: "Artifacts url"
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Setup artifacts url
      uses: scality/action-artifacts@v3
      id: artifacts
      with:
        method: setup
        url: https://artifacts.scality.net
        user: ${{ inputs.ARTIFACTS_USER }}
        password: ${{ inputs.ARTIFACTS_PASSWORD }}
    - name: "Retrieve MetalK8s ISO"
      shell: bash
      run: >
        curl --fail -LO -u ${{ inputs.ARTIFACTS_USER }}:${{ inputs.ARTIFACTS_PASSWORD }}
        ${{inputs.ARTIFACT_URL || steps.artifacts.outputs.link}}/metalk8s.iso
    - name: "Retrieve checksum"
      shell: bash
      run: >
        curl --fail -LO -u ${{ inputs.ARTIFACTS_USER }}:${{ inputs.ARTIFACTS_PASSWORD }}
        ${{inputs.ARTIFACT_URL || steps.artifacts.outputs.link}}/SHA256SUM
    - name: Check the checksum
      shell: bash
      run: |
        sha256sum -c SHA256SUM
        checkisomd5 metalk8s.iso
